name: shelf_dev
version: 1.0.0-dev
# homepage: https://www.example.com

environment:
  sdk: '>=2.12.0 <3.0.0'

dependencies:
  shelf_proxy: ^1.0.0
  path: ^1.7.0

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.6.0

dependency_overrides:
  shelf_proxy:
    git:
      url: https://github.com/dart-lang/shelf_proxy
      ref: null_safety
